"""
navigator_export.py
--------------------
Exports pipeline results as a MITRE ATT&CK Navigator layer file (layer
format v4.5). Upload the output JSON at
https://mitre-attack.github.io/attack-navigator/ to get a visual
red/green heatmap of real detection coverage — this is the artifact to
screenshot for a resume/portfolio/interview.
"""

import json


def build_navigator_layer(results, name="Detection Coverage"):
    techniques = []
    for r in results:
        techniques.append({
            "techniqueID": r["technique_id"],
            "score": 100 if r["detected"] else 0,
            "comment": f"Rule: {r.get('rule_file') or 'none — coverage gap'}",
            "enabled": True,
            "metadata": [],
        })

    return {
        "name": name,
        "versions": {"attack": "14", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Auto-generated by the self-scoring detection coverage pipeline.",
        "gradient": {
            "colors": ["#ff6666", "#66ff66"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Detected", "color": "#66ff66"},
            {"label": "Coverage gap", "color": "#ff6666"},
        ],
        "techniques": techniques,
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
    }


def write_navigator_layer(path, results, name="Detection Coverage"):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(build_navigator_layer(results, name), f, indent=2)
